version: "3"
services:
  database:
    # Dockerfile이 있는 위치
    image: skjin20800/every:db1.0
    # 외부에 공개할 host명
    hostname: dbhost
    ports:
      - "3306:3306"
    volumes:
      - spring-mysql-data:/var/lib/mysql
    networks:
      - test_net # 커스텀 네트워크 사용
  everytime:
    hostname: springboothost
    image: skjin20800/every:boot1.0
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - test_net # 커스텀 네트워크 사용//
  nginx:
    image: skjin20800/every:nginx1.0
    hostname: nginxhost
    ports:
      - "80:80"
    networks:
      - test_net
    depends_on:
      - everytime

networks:
  test_net: # 내가 만든 커스텀 네트워크명
    driver: bridge # 커스템 네트워크 연결방식 bridge, Host방식등 4~5개 정도있는데 보통 bridge방식을 많이 사용한다.

volumes:
  spring-mysql-data:
